### PR TITLE
Fix and enhancements for package/boot/uboot-lantiq-easybox904xdsl

### PR DESCRIPTION
**Pull request by arnysch**
- Fixes issue #9.
- Package's main Makefile refactored (though still more could be done).
- U-Boot Kconfig default values set to the suggested values for EasyBox 904.
- The recovery procedure (reset press during power-on) now also accepts an initramfs (renamed to fullimage.img). When an initramfs is submitted, it is simply loaded and startet. No flashing is done.
- No longer a password query before reaching the U-Boot command prompt.
- Reduced the repetitive saving of environment vars to flash.
- Refactored switch reset and initialization: duplicated code centralized in a functions.

### CODE REVIEW

**Comment by Quallenauge** [comment]
If I enable this option in config, do the default values produce a working uboot image?
(I haven't tried this yet).

**Comment by arnysch** [comment]
Tried it twice; once bfore commit 29b50dd , 2nd time after that commit. Works ok. But pls **do not apply my pull request yet.** While a normal OpenWrt created fullimage.img and a ramimages (renamed to fullimage.img) is gladly accepted, it seems my changes break handling the [fullimage at mega.nz](https://mega.nz/#!DBVCmZAB!8pLr-vmOcSTwJ8Szr-J32LRNLfZYJCH8tjaDGSnwIv8). Going to look into this...

**Comment by arnysch** [comment]
Oki, now looks good. Deleted .config, then used make menuconfig to select lantix/xrx200/eb904 and  then the U-Boot for eb904. Flashed it. Successfully tested the recovery procedure:
- load and flash 'normal' fullimage.img.
- load and run an initramfs (renamed to fullimage.img)
- load and run the old recovery image (which contains an initramfs) from [mega.nz](https://mega.nz/#!DBVCmZAB!8pLr-vmOcSTwJ8Szr-J32LRNLfZYJCH8tjaDGSnwIv8).

**Comment by Quallenauge** [comment]
@arnysch : Some objections to not merge this one?

**Comment by arnysch** [comment]
Please go ahead...

**Pull request merged**
